### ISSUE TITLE
Request open data api feature

### ISSUE THREAD

**Issue by philographer** [produce105/missK-Server#1]
## Todo Feature
- Request open data api

**Comment by yoohoogun114** [comment]
Feature Added. [b808b55](https://github.com/produce105/missK-Server/commit/b808b55c5d7919bdbe28bb199f57c9efd062bf0f)
Closed.

**Comment by philographer** [comment]
Resolved. https://github.com/produce105/missK-Server/commit/14eee0442734f4d148f1ac4362495730a916bf75
Closed.
