### ISSUE TITLE
/dustpredicate값 파싱해서 db에 넣기

### ISSUE THREAD

**Issue by Hsue66** [produce105/missK-Server#4]
let body = JSON.parse(res.body());
console.log(body[‘data’][‘MinuDustFrcstDspthVo’][‘list’][0] );

이런식으로 body값을 각각 파싱해주세요...
db에는 제가 넣을께요!

**Comment by philographer** [comment]
resolved in https://github.com/produce105/missK-Server/commit/ce40640e133c1a8fcc86be39c25ebde6814953d3
